#pragma once

#include "../foundation/Diagnostic.hpp"

#include <cstddef>
#include <string>
#include <vector>

namespace novac::source {

/**
 * @brief One logical source unit supplied to the NovaC engine.
 *
 * id is the canonical identity used for import de-duplication and cycle
 * detection while name is the human-readable path stored in diagnostics.
 */
struct Source {
    /** Canonical identity used for cycle detection and import de-duplication. */
    std::string id{};

    /** Human-readable source name used in diagnostics; may be empty before resolution. */
    std::string name{};

    /** Complete source contents. */
    std::string text{};
};

/** @brief Request passed to registered source resolvers. */
struct SourceRequest {
    /** Logical source specifier requested by the caller/directive. */
    std::string specifier{};

    /** Canonical id of the including/importing source, or empty for a root request. */
    std::string importer{};
};

/**
 * @brief Contiguous preprocessed text that still refers to its original source.
 */
struct SourceFragment {
    /** Text surviving/generated by preprocessing. */
    std::string text{};

    /** Original location corresponding to the first byte of text. */
    diagnostics::SourceLocation origin{};
};

/** @brief Preprocessor output preserving original source provenance. */
struct PreprocessedSource {
    /** Ordered fragments to tokenize after preprocessing. */
    std::vector<SourceFragment> fragments{};

    /** End-of-file location of the root source, independent of included fragments. */
    diagnostics::SourceLocation terminalLocation{};
};

/** @brief Per-run preprocessing limits and syntax. */
struct PreprocessOptions {
    /** Prefix introducing directives at the beginning of a logical line. */
    std::string directivePrefix{"#"};

    /** Maximum recursive include/import depth below the root source. Zero disables the limit. */
    std::size_t maxIncludeDepth{128};

    /** Symbols defined before preprocessing begins. */
    std::vector<std::string> defines{};
};

} // namespace novac::source
